<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="5" ignored="0" total="8" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="55070" started-at="2022-12-03T18:09:25 IST" finished-at="2022-12-03T18:10:20 IST">
    <groups>
    </groups>
    <test name="Test" duration-ms="55070" started-at="2022-12-03T18:09:25 IST" finished-at="2022-12-03T18:10:20 IST">
      <class name="test.DeleteAccountTest">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:test.DeleteAccountTest@56aac163]" name="beforeMethod" is-config="true" duration-ms="1999" started-at="2022-12-03T18:09:43 IST" finished-at="2022-12-03T18:09:45 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="verifyDeleteAccountMsg()[pri:0, instance:test.DeleteAccountTest@56aac163]" name="verifyDeleteAccountMsg" duration-ms="3176" started-at="2022-12-03T18:09:45 IST" finished-at="2022-12-03T18:09:48 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Account Deleted ] but found [Account not found ]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Account Deleted ] but found [Account not found ]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at test.DeleteAccountTest.verifyDeleteAccountMsg(DeleteAccountTest.java:17)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyDeleteAccountMsg -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:test.DeleteAccountTest@56aac163]" name="afterMethod" is-config="true" duration-ms="670" started-at="2022-12-03T18:09:48 IST" finished-at="2022-12-03T18:09:49 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- test.DeleteAccountTest -->
      <class name="test.AddAccountPageTest">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:test.AddAccountPageTest@184f6be2]" name="beforeMethod" is-config="true" duration-ms="5198" started-at="2022-12-03T18:09:26 IST" finished-at="2022-12-03T18:09:31 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="verifyAddAccountSuccsesfulMsg(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:test.AddAccountPageTest@184f6be2]" name="verifyAddAccountSuccsesfulMsg" duration-ms="4285" started-at="2022-12-03T18:09:31 IST" data-provider="createAccount" finished-at="2022-12-03T18:09:36 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Mk11kailash]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[456532.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[300.0]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Account Registered.. ] but found [Failed , try again ]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Account Registered.. ] but found [Failed , try again ]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at test.AddAccountPageTest.verifyAddAccountSuccsesfulMsg(AddAccountPageTest.java:22)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAddAccountSuccsesfulMsg -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:test.AddAccountPageTest@184f6be2]" name="afterMethod" is-config="true" duration-ms="736" started-at="2022-12-03T18:09:36 IST" finished-at="2022-12-03T18:09:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:test.AddAccountPageTest@184f6be2]" name="beforeMethod" is-config="true" duration-ms="2199" started-at="2022-12-03T18:09:37 IST" finished-at="2022-12-03T18:09:39 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="verifyAddAccountSuccsesfulMsg(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:test.AddAccountPageTest@184f6be2]" name="verifyAddAccountSuccsesfulMsg" duration-ms="3672" started-at="2022-12-03T18:09:39 IST" data-provider="createAccount" finished-at="2022-12-03T18:09:42 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[mk1234]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[78745.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[400.0]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Account Registered.. ] but found [Failed , try again ]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Account Registered.. ] but found [Failed , try again ]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at test.AddAccountPageTest.verifyAddAccountSuccsesfulMsg(AddAccountPageTest.java:22)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAddAccountSuccsesfulMsg -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:test.AddAccountPageTest@184f6be2]" name="afterMethod" is-config="true" duration-ms="651" started-at="2022-12-03T18:09:42 IST" finished-at="2022-12-03T18:09:43 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- test.AddAccountPageTest -->
      <class name="test.HomePageTest">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:test.HomePageTest@5a1c0542]" name="beforeMethod" is-config="true" duration-ms="1929" started-at="2022-12-03T18:10:04 IST" finished-at="2022-12-03T18:10:06 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="verifyHomePageHeaderTitle()[pri:0, instance:test.HomePageTest@5a1c0542]" name="verifyHomePageHeaderTitle" duration-ms="2197" started-at="2022-12-03T18:10:06 IST" finished-at="2022-12-03T18:10:08 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [TDIT Solutions ] but found [TDIT Solutions]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [TDIT Solutions ] but found [TDIT Solutions]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at test.HomePageTest.verifyHomePageHeaderTitle(HomePageTest.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyHomePageHeaderTitle -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:test.HomePageTest@5a1c0542]" name="afterMethod" is-config="true" duration-ms="647" started-at="2022-12-03T18:10:08 IST" finished-at="2022-12-03T18:10:09 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- test.HomePageTest -->
      <class name="test.LoginPageTest">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:test.LoginPageTest@1f7030a6]" name="beforeMethod" is-config="true" duration-ms="2004" started-at="2022-12-03T18:09:49 IST" finished-at="2022-12-03T18:09:51 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="VerifyLogin()[pri:0, instance:test.LoginPageTest@1f7030a6]" name="VerifyLogin" duration-ms="2172" started-at="2022-12-03T18:09:51 IST" finished-at="2022-12-03T18:09:53 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyLogin -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:test.LoginPageTest@1f7030a6]" name="afterMethod" is-config="true" duration-ms="682" started-at="2022-12-03T18:09:53 IST" finished-at="2022-12-03T18:09:54 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:test.LoginPageTest@1f7030a6]" name="beforeMethod" is-config="true" duration-ms="1950" started-at="2022-12-03T18:09:54 IST" finished-at="2022-12-03T18:09:56 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="verifyAlertIsPresentAndAlertText()[pri:0, instance:test.LoginPageTest@1f7030a6]" name="verifyAlertIsPresentAndAlertText" duration-ms="7424" started-at="2022-12-03T18:09:56 IST" finished-at="2022-12-03T18:10:03 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:751)
at org.testng.Assert.assertEquals(Assert.java:761)
at test.LoginPageTest.verifyAlertIsPresentAndAlertText(LoginPageTest.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAlertIsPresentAndAlertText -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:test.LoginPageTest@1f7030a6]" name="afterMethod" is-config="true" duration-ms="672" started-at="2022-12-03T18:10:03 IST" finished-at="2022-12-03T18:10:04 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- test.LoginPageTest -->
      <class name="test.UpdateAccountPageTest">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:test.UpdateAccountPageTest@396f6598]" name="beforeMethod" is-config="true" duration-ms="2074" started-at="2022-12-03T18:10:09 IST" finished-at="2022-12-03T18:10:11 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="verifyUpdateAcBalanceAlertMsg(java.lang.String, java.lang.String)[pri:0, instance:test.UpdateAccountPageTest@396f6598]" name="verifyUpdateAcBalanceAlertMsg" duration-ms="3413" started-at="2022-12-03T18:10:11 IST" data-provider="updateAccount" finished-at="2022-12-03T18:10:14 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[524697.0]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[444.0]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUpdateAcBalanceAlertMsg -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:test.UpdateAccountPageTest@396f6598]" name="afterMethod" is-config="true" duration-ms="666" started-at="2022-12-03T18:10:14 IST" finished-at="2022-12-03T18:10:15 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:test.UpdateAccountPageTest@396f6598]" name="beforeMethod" is-config="true" duration-ms="1976" started-at="2022-12-03T18:10:15 IST" finished-at="2022-12-03T18:10:17 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="verifyUpdateAcHeaderText()[pri:0, instance:test.UpdateAccountPageTest@396f6598]" name="verifyUpdateAcHeaderText" duration-ms="2826" started-at="2022-12-03T18:10:17 IST" finished-at="2022-12-03T18:10:20 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUpdateAcHeaderText -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:test.UpdateAccountPageTest@396f6598]" name="afterMethod" is-config="true" duration-ms="656" started-at="2022-12-03T18:10:20 IST" finished-at="2022-12-03T18:10:20 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- test.UpdateAccountPageTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
